# Generated by Django 4.2.30 on 2026-06-25 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fantacalcio', '0003_franchise_alter_ingaggio_unique_together_and_more'),
        ('core', '0003_stagione_crediti_default_stagione_data_fine_serie_a_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Es. GOLD, BRONZE, CIEMPIONS, UEFA, COPPA_ITALIA…', max_length=50)),
                ('tipo', models.CharField(choices=[('LEGA', 'Lega (campionato)'), ('COPPA', 'Coppa'), ('SUPERCOPPA', 'Super Coppa')], default='LEGA', max_length=12)),
                ('stato', models.CharField(choices=[('NON_INIZIATA', 'Non iniziata'), ('IN_CORSO', 'In corso'), ('COMPLETATA', 'Completata')], default='NON_INIZIATA', max_length=12)),
                ('stagione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competizioni', to='core.stagione')),
            ],
            options={
                'verbose_name': 'Competizione',
                'verbose_name_plural': 'Competizioni',
                'unique_together': {('stagione', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Giornata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Numero giornata nella competizione')),
                ('giornata_serie_a', models.PositiveIntegerField(help_text='Giornata di Serie A corrispondente')),
                ('data', models.DateField(blank=True, null=True)),
                ('stato', models.CharField(choices=[('PROGRAMMATA', 'Programmata'), ('COMPLETATA', 'Completata'), ('RINVIATA', 'Rinviata')], default='PROGRAMMATA', max_length=12)),
                ('competizione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giornate', to='competizioni.competizione')),
            ],
            options={
                'verbose_name': 'Giornata',
                'verbose_name_plural': 'Giornate',
                'ordering': ['competizione', 'numero'],
                'unique_together': {('competizione', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Partita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punteggio_casa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('punteggio_ospite', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('gol_casa', models.PositiveIntegerField(blank=True, null=True)),
                ('gol_ospite', models.PositiveIntegerField(blank=True, null=True)),
                ('risultato', models.CharField(blank=True, choices=[('CASA', 'Vittoria casa'), ('OSPITE', 'Vittoria ospite'), ('PAREGGIO', 'Pareggio')], max_length=8, null=True)),
                ('giornata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partite', to='competizioni.giornata')),
                ('squadra_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partite_casa', to='fantacalcio.fantasquadra')),
                ('squadra_ospite', models.ForeignKey(blank=True, help_text='Vuoto in caso di turno di riposo (bye)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partite_ospite', to='fantacalcio.fantasquadra')),
            ],
            options={
                'verbose_name': 'Partita',
                'verbose_name_plural': 'Partite',
            },
        ),
        migrations.CreateModel(
            name='Formazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giornata_serie_a', models.PositiveIntegerField(help_text='Giornata di Serie A di riferimento per i voti')),
                ('modulo', models.CharField(blank=True, help_text='Es. 4-3-3', max_length=10)),
                ('inviata_il', models.DateTimeField(blank=True, null=True)),
                ('fonte', models.CharField(choices=[('WEB', 'Web'), ('TELEGRAM', 'Telegram'), ('PREC', 'Settimana precedente')], default='WEB', max_length=10)),
                ('partita', models.ForeignKey(blank=True, help_text='Vuoto per competizioni indipendenti (es. Ciempions/UEFA)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formazioni', to='competizioni.partita')),
                ('squadra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formazioni', to='fantacalcio.fantasquadra')),
            ],
            options={
                'verbose_name': 'Formazione',
                'verbose_name_plural': 'Formazioni',
            },
        ),
        migrations.CreateModel(
            name='PunteggioSquadraPartita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totale_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('modificatore_difesa', models.IntegerField(default=0)),
                ('gol_fanta', models.PositiveIntegerField(default=0)),
                ('dettagli', models.JSONField(blank=True, default=dict, help_text='Dettaglio calcolo (voti, sostituzioni, modificatore)')),
                ('partita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punteggi', to='competizioni.partita')),
                ('squadra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punteggi_partita', to='fantacalcio.fantasquadra')),
            ],
            options={
                'verbose_name': 'Punteggio squadra',
                'verbose_name_plural': 'Punteggi squadra',
                'unique_together': {('partita', 'squadra')},
            },
        ),
        migrations.CreateModel(
            name='FormazioneGiocatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posizione', models.CharField(choices=[('TITOLARE', 'Titolare'), ('PANCHINA', 'Panchina')], max_length=10)),
                ('ordine_panchina', models.PositiveIntegerField(blank=True, help_text='Ordine subentro (1=primo)', null=True)),
                ('is_riserva_ufficio', models.BooleanField(default=False)),
                ('formazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giocatori', to='competizioni.formazione')),
                ('ingaggio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocazioni', to='fantacalcio.ingaggio')),
            ],
            options={
                'verbose_name': 'Giocatore in formazione',
                'verbose_name_plural': 'Giocatori in formazione',
                'ordering': ['posizione', 'ordine_panchina'],
                'unique_together': {('formazione', 'ingaggio')},
            },
        ),
        migrations.CreateModel(
            name='Classifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giocate', models.PositiveIntegerField(default=0)),
                ('vinte', models.PositiveIntegerField(default=0)),
                ('pareggiate', models.PositiveIntegerField(default=0)),
                ('perse', models.PositiveIntegerField(default=0)),
                ('punti', models.IntegerField(default=0)),
                ('totale_fanta_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('gol_fatti', models.IntegerField(default=0)),
                ('gol_subiti', models.IntegerField(default=0)),
                ('aggiornata_il', models.DateTimeField(auto_now=True)),
                ('competizione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifica', to='competizioni.competizione')),
                ('squadra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posizioni_classifica', to='fantacalcio.fantasquadra')),
            ],
            options={
                'verbose_name': 'Classifica',
                'verbose_name_plural': 'Classifiche',
                'ordering': ['-punti', '-totale_fanta_score'],
                'unique_together': {('competizione', 'squadra')},
            },
        ),
    ]
