# Generated by Django 4.2.30 on 2026-06-25 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_stagione_crediti_default_stagione_data_fine_serie_a_and_more'),
        ('fantacalcio', '0003_franchise_alter_ingaggio_unique_together_and_more'),
        ('players', '0005_remove_calciatore_cognome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lega', models.CharField(help_text='Es. GOLD / BRONZE / CARBON', max_length=50)),
                ('tipo', models.CharField(choices=[('INIZIALE', 'Asta iniziale'), ('RIPARAZIONE', 'Mercato di riparazione')], default='INIZIALE', max_length=12)),
                ('data', models.DateField(blank=True, null=True)),
                ('stato', models.CharField(choices=[('PROGRAMMATA', 'Programmata'), ('IN_CORSO', 'In corso'), ('COMPLETATA', 'Completata')], default='PROGRAMMATA', max_length=12)),
                ('fantalab_url', models.URLField(blank=True, null=True)),
                ('stagione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aste', to='core.stagione')),
            ],
            options={
                'verbose_name': 'Asta',
                'verbose_name_plural': 'Aste',
            },
        ),
        migrations.CreateModel(
            name='Scambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_scambio', models.DateField(blank=True, null=True)),
                ('stato', models.CharField(choices=[('PROPOSTO', 'Proposto'), ('CONFERMATO', 'Confermato'), ('RIFIUTATO', 'Rifiutato')], default='PROPOSTO', max_length=12)),
                ('confermato_il', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('squadra_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scambi_come_a', to='fantacalcio.fantasquadra')),
                ('squadra_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scambi_come_b', to='fantacalcio.fantasquadra')),
                ('stagione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scambi', to='core.stagione')),
            ],
            options={
                'verbose_name': 'Scambio',
                'verbose_name_plural': 'Scambi',
            },
        ),
        migrations.CreateModel(
            name='ScambioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prezzo_assegnato', models.PositiveIntegerField(blank=True, help_text='Prezzo post-scambio calcolato', null=True)),
                ('ingaggio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_scambi', to='fantacalcio.ingaggio')),
                ('scambio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mercato.scambio')),
                ('squadra_cedente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cessioni_scambio', to='fantacalcio.fantasquadra')),
            ],
            options={
                'verbose_name': 'Giocatore in scambio',
                'verbose_name_plural': 'Giocatori in scambio',
            },
        ),
        migrations.CreateModel(
            name='OffertaAsta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prezzo_finale', models.PositiveIntegerField()),
                ('ordine_chiamata', models.PositiveIntegerField(blank=True, null=True)),
                ('asta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerte', to='mercato.asta')),
                ('calciatore_stagione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerte_asta', to='players.calciatorestagione')),
                ('chiamata_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chiamate', to='fantacalcio.fantasquadra')),
                ('squadra_vincitrice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggiudicazioni', to='fantacalcio.fantasquadra')),
            ],
            options={
                'verbose_name': "Offerta d'asta",
                'verbose_name_plural': "Offerte d'asta",
            },
        ),
    ]
