# Generated by Django 4.2.30 on 2026-06-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantapresidente',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, help_text='ID utente Telegram per il collegamento al bot. Dato personale: accesso ristretto allo staff.', null=True, unique=True),
        ),
    ]
