# Generated by Django 4.2.30 on 2026-05-06 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisiPreAsta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obiettivo', models.CharField(blank=True, max_length=50, verbose_name='Obiett.')),
                ('fascia', models.PositiveIntegerField(blank=True, null=True, verbose_name='Fascia')),
                ('prezzo_massimo', models.PositiveIntegerField(default=0, verbose_name='Prezzo')),
                ('budget_percentuale', models.DecimalField(blank=True, decimal_places=2, help_text='Su base budget 350', max_digits=5, null=True, verbose_name='Budget %')),
                ('pma', models.DecimalField(blank=True, decimal_places=2, help_text='Prezzo Medio Altre Leghe', max_digits=6, null=True, verbose_name='PMA')),
                ('quotazione', models.PositiveIntegerField(default=0, verbose_name='Quo')),
                ('titolarita', models.PositiveIntegerField(blank=True, null=True, verbose_name='Titolarità')),
                ('affidabilita', models.PositiveIntegerField(blank=True, null=True, verbose_name='Affidabilità')),
                ('integrita', models.PositiveIntegerField(blank=True, null=True, verbose_name='Integrità')),
                ('commento', models.TextField(blank=True, verbose_name='Commento')),
                ('nota_1', models.CharField(blank=True, max_length=255, verbose_name='Nota 1')),
                ('nota_2', models.CharField(blank=True, max_length=255, verbose_name='Nota 2')),
                ('nota_3', models.CharField(blank=True, max_length=255, verbose_name='Nota 3')),
                ('nota_4', models.CharField(blank=True, max_length=255, verbose_name='Nota 4')),
                ('nota_5', models.CharField(blank=True, max_length=255, verbose_name='Nota 5')),
                ('fmv_exp', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='FMV Exp.')),
                ('pt_tit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Pt. Tit.')),
                ('minuti', models.PositiveIntegerField(blank=True, null=True, verbose_name='Minuti')),
                ('pt_inf', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Pt. Inf.')),
                ('calciatore_stagione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisi_pre_asta', to='players.calciatorestagione')),
            ],
            options={
                'verbose_name_plural': 'Analisi Pre-Asta',
            },
        ),
    ]
