# Generated by Django 4.2.30 on 2026-05-06 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisipreasta',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategie_asta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='analisipreasta',
            unique_together={('calciatore_stagione', 'utente')},
        ),
    ]
