# Generated by Django 4.2.30 on 2026-05-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisipreasta',
            name='fascia',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Fascia'),
        ),
    ]
