# Generated by Django 4.2.30 on 2026-05-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SquadraReale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('sigla', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Squadre Reali',
            },
        ),
        migrations.CreateModel(
            name='Stagione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Es: 2023/2024', max_length=9, unique=True)),
                ('attiva', models.BooleanField(default=False, help_text='Segna la stagione attualmente in corso')),
            ],
            options={
                'verbose_name_plural': 'Stagioni',
            },
        ),
    ]
