# Generated by Django 4.2.30 on 2026-06-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_importtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagione',
            name='crediti_default',
            field=models.PositiveIntegerField(default=350, help_text='Crediti (FM) iniziali di default per le squadre della stagione'),
        ),
        migrations.AddField(
            model_name='stagione',
            name='data_fine_serie_a',
            field=models.DateField(blank=True, help_text="Data dell'ultima giornata di Serie A", null=True),
        ),
        migrations.AddField(
            model_name='stagione',
            name='data_inizio_serie_a',
            field=models.DateField(blank=True, help_text='Data della 1a giornata di Serie A', null=True),
        ),
    ]
