# Generated by Django 4.2.30 on 2026-05-06 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FantaSquadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('crediti_residui', models.IntegerField(default=500)),
            ],
            options={
                'verbose_name_plural': 'Fantasquadre',
            },
        ),
        migrations.CreateModel(
            name='Lega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Leghe',
            },
        ),
        migrations.CreateModel(
            name='Ingaggio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_acquisto', models.PositiveIntegerField()),
                ('calciatore_stagione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingaggi', to='players.calciatorestagione')),
                ('fantasquadra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosa', to='fantacalcio.fantasquadra')),
            ],
            options={
                'verbose_name_plural': 'Ingaggi',
            },
        ),
        migrations.AddField(
            model_name='fantasquadra',
            name='lega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squadre', to='fantacalcio.lega'),
        ),
    ]
