# Generated by Django 4.2.30 on 2026-05-06 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('fantacalcio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasquadra',
            name='presidenti',
            field=models.ManyToManyField(related_name='fantasquadre', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fantasquadra',
            name='stagione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasquadre', to='core.stagione'),
        ),
        migrations.AlterUniqueTogether(
            name='ingaggio',
            unique_together={('fantasquadra', 'calciatore_stagione')},
        ),
        migrations.AlterUniqueTogether(
            name='fantasquadra',
            unique_together={('nome', 'stagione')},
        ),
    ]
