# Generated by Django 4.2.30 on 2026-06-25 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_stagione_crediti_default_stagione_data_fine_serie_a_and_more'),
        ('fantacalcio', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome storico, es. 'I Dragoni'", max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='franchise_logos/')),
            ],
            options={
                'verbose_name': 'Franchigia',
                'verbose_name_plural': 'Franchigie',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ingaggio',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fantasquadra',
            name='crediti_iniziali',
            field=models.PositiveIntegerField(default=350),
        ),
        migrations.AddField(
            model_name='fantasquadra',
            name='note_palmares',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ingaggio',
            name='attivo',
            field=models.BooleanField(default=True, help_text='True se attualmente in rosa'),
        ),
        migrations.AddField(
            model_name='ingaggio',
            name='data_acquisizione',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingaggio',
            name='data_cessione',
            field=models.DateField(blank=True, help_text='Valorizzata quando il giocatore lascia la rosa', null=True),
        ),
        migrations.AddField(
            model_name='ingaggio',
            name='is_sub_temporaneo',
            field=models.BooleanField(default=False, help_text='True se sostituzione temporanea da infortunio'),
        ),
        migrations.AddField(
            model_name='ingaggio',
            name='sostituisce',
            field=models.ForeignKey(blank=True, help_text="L'ingaggio (titolare infortunato) che questo giocatore sostituisce", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sostituito_da', to='fantacalcio.ingaggio'),
        ),
        migrations.AddField(
            model_name='ingaggio',
            name='tipo_acquisizione',
            field=models.CharField(choices=[('ASTA', 'Asta'), ('RIPARAZIONE', 'Mercato di riparazione'), ('SOSTITUZIONE', 'Sostituzione infortunio'), ('SCAMBIO', 'Scambio')], default='ASTA', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='ingaggio',
            constraint=models.UniqueConstraint(condition=models.Q(('attivo', True)), fields=('fantasquadra', 'calciatore_stagione'), name='unique_ingaggio_attivo_per_squadra'),
        ),
        migrations.AddField(
            model_name='franchise',
            name='stagione_fondazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='franchigie_fondate', to='core.stagione'),
        ),
        migrations.AddField(
            model_name='fantasquadra',
            name='franchise',
            field=models.ForeignKey(blank=True, help_text='Identità storica (vuoto = squadra nuova senza storia)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='squadre_stagionali', to='fantacalcio.franchise'),
        ),
    ]
