# Generated by Django 4.2.30 on 2026-05-06 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticaCalciatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partite_a_voto', models.PositiveIntegerField(default=0, verbose_name='Pv')),
                ('media_voto', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Mv')),
                ('fanta_media', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Fm')),
                ('gol_fatti', models.PositiveIntegerField(default=0, verbose_name='Gf')),
                ('gol_subiti', models.PositiveIntegerField(default=0, verbose_name='Gs')),
                ('rigori_parati', models.PositiveIntegerField(default=0, verbose_name='Rp')),
                ('rigori_calciati', models.PositiveIntegerField(default=0, verbose_name='Rc')),
                ('rigori_fatti', models.PositiveIntegerField(default=0, verbose_name='R+')),
                ('rigori_sbagliati', models.PositiveIntegerField(default=0, verbose_name='R-')),
                ('assist', models.PositiveIntegerField(default=0, verbose_name='Ass')),
                ('ammonizioni', models.PositiveIntegerField(default=0, verbose_name='Amm')),
                ('espulsioni', models.PositiveIntegerField(default=0, verbose_name='Esp')),
                ('autogol', models.PositiveIntegerField(default=0, verbose_name='Au')),
                ('calciatore_stagione', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistiche_riassuntive', to='players.calciatorestagione')),
            ],
        ),
        migrations.CreateModel(
            name='VotoPartita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giornata', models.PositiveIntegerField()),
                ('voto_base', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Voto')),
                ('fanta_voto', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('gol_fatti', models.PositiveIntegerField(default=0, verbose_name='Gf')),
                ('gol_subiti', models.PositiveIntegerField(default=0, verbose_name='Gs')),
                ('rigori_parati', models.PositiveIntegerField(default=0, verbose_name='Rp')),
                ('rigori_sbagliati', models.PositiveIntegerField(default=0, verbose_name='Rs')),
                ('rigori_fatti', models.PositiveIntegerField(default=0, verbose_name='Rf')),
                ('autogol', models.PositiveIntegerField(default=0, verbose_name='Au')),
                ('ammonizioni', models.PositiveIntegerField(default=0, verbose_name='Amm')),
                ('espulsioni', models.PositiveIntegerField(default=0, verbose_name='Esp')),
                ('assist', models.PositiveIntegerField(default=0, verbose_name='Ass')),
                ('calciatore_stagione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voti', to='players.calciatorestagione')),
            ],
            options={
                'verbose_name_plural': 'Voti Partita',
                'unique_together': {('calciatore_stagione', 'giornata')},
            },
        ),
    ]
