# Generated by Django 4.2.30 on 2026-05-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '↗️ Vai alla Dashboard Import',
                'verbose_name_plural': '↗️ Vai alla Dashboard Import',
                'managed': False,
            },
        ),
    ]
