# Generated by Django 4.2.30 on 2026-06-25 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fantacalcio', '0003_franchise_alter_ingaggio_unique_together_and_more'),
        ('players', '0005_remove_calciatore_cognome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infortunio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_bollettino', models.DateField(help_text='Data del bollettino ufficiale')),
                ('rientro_stimato', models.DateField(blank=True, null=True)),
                ('rientro_possibile', models.DateField(blank=True, help_text='Rientro anticipato possibile', null=True)),
                ('url_bollettino', models.URLField(blank=True, null=True)),
                ('settimane_out', models.PositiveIntegerField(blank=True, help_text='Calcolato o inserito a mano', null=True)),
                ('qualifica_sostituzione', models.BooleanField(default=False, help_text='>= 8 settimane (calcolato)')),
                ('rientro_effettivo', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('calciatore_stagione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infortuni', to='players.calciatorestagione')),
            ],
            options={
                'verbose_name': 'Infortunio',
                'verbose_name_plural': 'Infortuni',
            },
        ),
        migrations.CreateModel(
            name='SostituzioneTemporanea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prezzo_acquisto_sostituto', models.PositiveIntegerField(default=0)),
                ('attivata_il', models.DateField(blank=True, null=True)),
                ('terminata_il', models.DateField(blank=True, null=True)),
                ('motivo_fine', models.CharField(blank=True, choices=[('RIENTRO', 'Rientro del titolare'), ('FINE_STAGIONE', 'Fine stagione'), ('MANUALE', 'Manuale')], max_length=14, null=True)),
                ('numero_sostituzione', models.PositiveSmallIntegerField(default=1, help_text='1-3 (limite per squadra)')),
                ('calciatore_sostituto', models.ForeignKey(help_text='Lo svincolato acquisito come sostituto', on_delete=django.db.models.deletion.CASCADE, related_name='ingressi_sostituzione', to='players.calciatorestagione')),
                ('infortunio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sostituzioni', to='infortuni.infortunio')),
                ('ingaggio_sostituito', models.ForeignKey(help_text="L'ingaggio del titolare infortunato", on_delete=django.db.models.deletion.CASCADE, related_name='sostituzioni_subite', to='fantacalcio.ingaggio')),
                ('squadra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sostituzioni_temporanee', to='fantacalcio.fantasquadra')),
            ],
            options={
                'verbose_name': 'Sostituzione temporanea',
                'verbose_name_plural': 'Sostituzioni temporanee',
            },
        ),
    ]
