# Generated by Django 4.2.30 on 2026-05-06 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calciatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('ruolo_base', models.CharField(choices=[('P', 'Portiere'), ('D', 'Difensore'), ('C', 'Centrocampista'), ('A', 'Attaccante')], help_text='Ruolo di default, può essere sovrascritto nella stagione', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Calciatori',
                'unique_together': {('nome', 'cognome')},
            },
        ),
        migrations.CreateModel(
            name='CalciatoreStagione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruolo_stagione', models.CharField(choices=[('P', 'Portiere'), ('D', 'Difensore'), ('C', 'Centrocampista'), ('A', 'Attaccante')], max_length=1)),
                ('quotazione_iniziale', models.PositiveIntegerField(default=1)),
                ('calciatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stagioni', to='players.calciatore')),
                ('squadra_reale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster', to='core.squadrareale')),
                ('stagione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calciatori', to='core.stagione')),
            ],
            options={
                'verbose_name_plural': 'Calciatori per Stagione',
                'unique_together': {('calciatore', 'stagione')},
            },
        ),
    ]
