# Generated by Django 4.2.30 on 2026-05-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calciatore',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='calciatore',
            name='fanta_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID ufficiale di Fantacalcio', null=True, unique=True),
        ),
    ]
