# Generated by Django 4.2.30 on 2026-05-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_calciatore_unique_together_calciatore_fanta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calciatore',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
