# Generated by Django 4.2.30 on 2026-05-06 15:51

from django.db import migrations


def merge_names(apps, schema_editor):
    Calciatore = apps.get_model('players', 'Calciatore')
    for c in Calciatore.objects.all():
        if c.nome:
            c.nome = f"{c.cognome} {c.nome}".strip()
        else:
            c.nome = c.cognome.strip()
        c.save()

def unmerge_names(apps, schema_editor):
    pass  # Non reversibile in modo preciso

class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_calciatore_nome'),
    ]

    operations = [
        migrations.RunPython(merge_names, unmerge_names),
    ]
