# Generated by Django 4.2.30 on 2026-05-06 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_merge_nome_cognome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calciatore',
            name='cognome',
        ),
    ]
